from __future__ import annotations
import json, re
from pathlib import Path
from typing import Any
class ProjectArtifactBuilder:
    """Create a deterministic starter workspace from a project request."""
    def build(self, project_name: str, request: str, workflow: dict[str, Any]) -> dict[str, Any]:
        safe=re.sub(r"[^A-Za-z0-9_-]+","-",project_name).strip("-") or "jarvis-project"
        root=Path("generated_projects")/safe; root.mkdir(parents=True,exist_ok=True)
        files={"README.md":f"# {project_name}\n\nGenerated by JARVIS.\n\nRequest: {request}\n","JARVIS_PROJECT.json":json.dumps({"name":project_name,"request":request,"workflow":workflow},indent=2)}
        lower=request.lower()
        if any(x in lower for x in ("website","web app","frontend","html","react","saas")):
            files["index.html"]='<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>JARVIS App</title><link rel="stylesheet" href="style.css"></head><body><main><h1>JARVIS Generated App</h1><p id="status">Ready.</p><button id="run">Test interaction</button></main><script src="app.js"></script></body></html>\n'
            files["style.css"]='body{margin:0;font-family:system-ui,sans-serif;background:#0b1020;color:#eef2ff}main{max-width:900px;margin:15vh auto;padding:32px}button{padding:10px 16px;cursor:pointer}\n'
            files["app.js"]='document.querySelector("#run").addEventListener("click",()=>document.querySelector("#status").textContent="Interaction passed.");\n'
        if any(x in lower for x in ("python","backend","api","fastapi","flask"," app")):
            files["app.py"]='def health_check():\n    return {"status": "ok", "service": "jarvis-generated-app"}\n\nif __name__ == "__main__":\n    print(health_check())\n'
        manifest=[]
        for name,content in files.items():
            (root/name).write_text(content,encoding="utf-8"); manifest.append({"path":name,"bytes":len(content.encode("utf-8"))})
        (root/"artifact_manifest.json").write_text(json.dumps({"project":project_name,"files":manifest},indent=2),encoding="utf-8")
        return {"project_dir":str(root),"files":manifest,"file_count":len(manifest)}
